### ISSUE TITLE
Bumping isn't functional

### ISSUE THREAD

**Issue by Gwydion-Smit** [bioBean/elbowbumps#11]
The bump() func in the BumperCard.vue component is being called when clicking on the Bump button, yet the body of the method isn't implemented yet. The code from bump() in Matches.vue needs to be copied over there (I think). 

From your friendly course mate who also found out your api endpoints are open, giving out personal information xox :)

**Comment by Gwydion-Smit** [comment]
Bruh how am I meant to do anything when assigned to this smh my head zoe anwar

**Comment by GrayNekoBean** [comment]
yeah, I know this problem, many parts were not really finished yet, thx.
