### ISSUE TITLE
Bumping text isn't implemented

### ISSUE THREAD

**Issue by Gwydion-Smit** [bioBean/elbowbumps#14]
Similar to my previous bumping issue I opened, but err not the same :)))
The code that has been written (but currently in wrong place) doesn't do anything with the text that is entered. Similarly on server side you don't have the ability to handle it yet. And similarly, there's nothing to handle it when viewing bumps, back or front end.

:D

**Comment by Zoya-Anwar** [comment]
Yeah maybe we should just take this out for now? Since it doesn't do anything and it's not a priority?

**Comment by Zoya-Anwar** [comment]
Bumping text is now implemented @Gwydion-Smit
