### ISSUE TITLE
User profile editing no worky

### ISSUE THREAD

**Issue by Gwydion-Smit** [bioBean/elbowbumps#15]
Can't edit user profile, sad!
And I made this really because I think you could have same mistake as currently with emails and phone number on account creation. 

When editing profile make sure that only a proper phone number and email can be entered.

**Comment by GrayNekoBean** [comment]
Yes, the save button currently not working because the backend function of update user info is still empty, I really need someone who knows how to manipulate the database to finish that TODO in auth.py line 187. For the frontend validation, I will fix that soon.

**Comment by Zoya-Anwar** [comment]
user profile edit now worky @Gwydion-Smit
